//
//  AboutView.swift
//  Zephos
//
//  Created by Charles Watson on 15/7/2022.
//

import SwiftUI

struct AboutView: View {
    var body: some View {
        VStack{
            Text("About this app")
                .font(.title)
                .padding()
            Spacer()
            Text("Weather data powered by OpenWeatherMap.org")
                .padding()
            Text("JSON response struct generated by QuickType.io")
                .padding()
            Spacer()
        }.preferredColorScheme(.dark)
    }
}

struct AboutView_Previews: PreviewProvider {
    static var previews: some View {
        AboutView()
    }
}
